INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Montgomery','Alabama', 'AL')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Juneau','Alaska', 'AK')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Phoenix','Arizona', 'AZ')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Little Rock','Arkansas', 'AR')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Sacramento','California', 'CA')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Denver','Colorado', 'CO')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Hartford','Connecticut', 'CT')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Dover','Delaware', 'DE')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Tallahassee','Florida', 'FL')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Atlanta','Georgia', 'GA')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Honolulu','Hawaii', 'HI')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Boise','Idaho', 'ID')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Springfield','Illinois', 'IL')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Indianapolis','Indiana', 'IN')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Des Moines','Iowa', 'IA')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Topeka','Kansas', 'KS')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Frankfort','Kentucky', 'KY')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Baton Rouge','Louisiana', 'LA')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Augusta','Maine', 'ME')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Annapolis','Maryland', 'MD')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Boston','Massachusetts', 'MA')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Lansing','Michigan', 'MI')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('St. Paul','Minnesota', 'MN')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Jackson','Mississippi', 'MS')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Jefferson City','Missouri', 'MO')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Helena','Montana', 'MT')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Lincoln','Nebraska', 'NE')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Carson City','Nevada', 'NV')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Concord','New Hampshire', 'NH')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Trenton','New Jersey', 'NJ')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Santa Fe','New Mexico', 'NM')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Albany','New York', 'NY')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Raleigh','North Carolina', 'NC')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Bismarck','North Dakota', 'ND')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Columbus','Ohio', 'OH')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Oklahoma City','Oklahoma', 'OK')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Salem','Oregon', 'OR')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Harrisburg','Pennsylvania', 'PA')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Providence','Rhode Island', 'RI')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Columbia','South Carolina', 'SC')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Pierre','South Dakota', 'SD')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Nashville','Tennessee', 'TN')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Austin','Texas', 'TX')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Salt Lake City','Utah', 'UT')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Montpelier','Vermont', 'VT')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Richmond','Virginia', 'VA')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Olympia','Washington', 'WA')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Charleston','West Virginia', 'WV')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Madison','Wisconsin', 'WI')
INSERT INTO [dbo].[capitals] ([name], [state], [abbreviation]) VALUES ('Cheyenne','Wyoming', 'WY')